/**
 * ISO 3166-1 alpha-2 → the ISO 3166-1 numeric `id` used by world-atlas's
 * countries-110m.json (Natural Earth data, public domain). Plain geographic
 * reference data, not a legal/regulatory fact — not subject to the Accuracy
 * Policy (AGENTS.md §3). Generated by name-matching against
 * data/countries.json, data/destinations.json, and data/nationality-rules.json
 * (see git history for the generating script); verified against feature
 * counts before committing.
 *
 * The 110m (low) resolution atlas omits a few very small countries — none of
 * which are currently a nationality or destination in this project's data —
 * so WorldMap gracefully skips highlighting any code missing from this table.
 */
export const COUNTRY_GEO_IDS: Record<string, string> = {
  AT: "040",
  BE: "056",
  BG: "100",
  HR: "191",
  CZ: "203",
  DK: "208",
  EE: "233",
  FI: "246",
  FR: "250",
  DE: "276",
  GR: "300",
  HU: "348",
  IS: "352",
  IT: "380",
  LV: "428",
  LT: "440",
  LU: "442",
  NL: "528",
  NO: "578",
  PL: "616",
  PT: "620",
  RO: "642",
  SK: "703",
  SI: "705",
  ES: "724",
  SE: "752",
  CH: "756",
  CY: "196",
  IE: "372",
  GB: "826",
  US: "840",
  CA: "124",
  AU: "036",
  NZ: "554",
  JP: "392",
  KR: "410",
  BR: "076",
  MX: "484",
  AR: "032",
  CL: "152",
  MY: "458",
  IL: "376",
  UA: "804",
  KE: "404",
  TH: "764",
  AE: "784",
  TR: "792",
  ZA: "710",
  RW: "646",
  EG: "818",
  NG: "566",
  MA: "504",
  IN: "356",
  SG: "702",
};
